/* --------------------------------------------------------
* Author Tien Tran
* Email tientran0019@gmail.com
* Phone 0972970075
*
* Created: 2022-09-23 07:23:58
*------------------------------------------------------- */

const data = {
	'Core C1': [
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 20.67,
			alpha: 4.58,
			sharpeRatio: 0.32,
			jensenAlpha: 4.63,
			informationRatio: 1.27,
			trackingError: 3.60,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 20.67,
			alpha: 4.45,
			sharpeRatio: 1.04,
			jensenAlpha: 3.04,
			informationRatio: 0.81,
			trackingError: 5.46,
		},
		{
			name: 'IShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB GLOBAL AGGS',
			currency: 'SGD',
			weight: 4.61,
			alpha: 2.78,
			sharpeRatio: 1.30,
			jensenAlpha: 0.10,
			informationRatio: 0.34,
			trackingError: 8.13,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 20.67,
			alpha: 1.32,
			sharpeRatio: 0.73,
			jensenAlpha: 0.95,
			informationRatio: 0.34,
			trackingError: 3.86,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 3.38,
			alpha: 0.00,
			sharpeRatio: 3.99,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'AIA International Health Care Fund',
			index: 'MSCI World/Health Care NR SGD',
			currency: 'SGD',
			weight: 4.00,
			alpha: 2.52,
			sharpeRatio: 0.01,
			jensenAlpha: 1.78,
			informationRatio: 0.37,
			trackingError: 6.81,
		},
		{
			name: 'iShares S&P 500 Value ETF',
			index: 'S&P 500 Value TR SGD',
			currency: 'SGD',
			weight: 2.00,
			alpha: 2.42,
			sharpeRatio: 0.08,
			jensenAlpha: 2.40,
			informationRatio: 2.04,
			trackingError: 1.19,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Pac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 2.47,
			sharpeRatio: 0.02,
			jensenAlpha: 2.15,
			informationRatio: 0.35,
			trackingError: 6.99,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.15,
			sharpeRatio: 0.08,
			jensenAlpha: 0.26,
			informationRatio: 0.02,
			trackingError: 6.55,
		},
		{
			name: 'Vanguard Consumer Staples ETF',
			index: 'S&P500 Consumer Staples',
			currency: 'SGD',
			weight: 2.00,
			alpha: 2.57,
			sharpeRatio: 0.12,
			jensenAlpha: 2.52,
			informationRatio: 1.52,
			trackingError: 1.69,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 10.00,
			alpha: 0.60,
			sharpeRatio: 0.01,
			jensenAlpha: 0.59,
			informationRatio: 0.11,
			trackingError: 5.21,
		},
	],
	'Core C2': [
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 20.00,
			alpha: 4.96,
			sharpeRatio: 0.53,
			jensenAlpha: 4.91,
			informationRatio: 1.69,
			trackingError: 2.94,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 20.00,
			alpha: 4.72,
			sharpeRatio: 0.94,
			jensenAlpha: 3.94,
			informationRatio: 1.10,
			trackingError: 4.30,
		},
		{
			name: 'PIMCO GIS GllnGd Crdt E SGD Inc',
			index: 'BB Global IG',
			currency: 'SGD',
			weight: 5.44,
			alpha: 2.12,
			sharpeRatio: 1.18,
			jensenAlpha: 2.72,
			informationRatio: 0.90,
			trackingError: 2.36,
		},
		{
			name: 'IShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB GLOBAL AGGS',
			currency: 'SGD',
			weight: 5.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 5.00,
			alpha: 1.79,
			sharpeRatio: 0.81,
			jensenAlpha: 1.91,
			informationRatio: 0.59,
			trackingError: 3.02,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 5.00,
			alpha: 0.00,
			sharpeRatio: 3.68,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'iShares S&P 500 Value ETF',
			index: 'S&P 500 Value TR SGD',
			currency: 'SGD',
			weight: 5.00,
			alpha: 2.48,
			sharpeRatio: 0.06,
			jensenAlpha: 2.48,
			informationRatio: 2.11,
			trackingError: 1.18,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 1.00,
			alpha: 0.27,
			sharpeRatio: 0.01,
			jensenAlpha: 0.27,
			informationRatio: 0.14,
			trackingError: 1.92,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 2.00,
			alpha: 2.15,
			sharpeRatio: 0.02,
			jensenAlpha: 1.97,
			informationRatio: 0.53,
			trackingError: 4.07,
		},
		{
			name: 'SPDR MSCI World Comm Svcs ETF SGD Acc',
			index: 'MSCI World Comm Services',
			currency: 'SGD',
			weight: 4.00,
			alpha: 0.04,
			sharpeRatio: 0.09,
			jensenAlpha: 0.09,
			informationRatio: 0.01,
			trackingError: 5.33,
		},
		{
			name: 'Health Care Select Sector SPDR ETF',
			index: 'S&P500 Health Care',
			currency: 'SGD',
			weight: 6.96,
			alpha: 1.76,
			sharpeRatio: 0.23,
			jensenAlpha: 1.69,
			informationRatio: 1.63,
			trackingError: 1.08,
		},
		{
			name: 'Communities Services Sel Sect SPDR ETF',
			index: 'S&P500 Communities Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.36,
			sharpeRatio: 0.15,
			jensenAlpha: 1.61,
			informationRatio: 0.81,
			trackingError: 1.67,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 7.48,
			alpha: 0.71,
			sharpeRatio: 0.05,
			jensenAlpha: 0.68,
			informationRatio: 0.15,
			trackingError: 4.89,
		},
	],
	'Core C3': [
		{
			name: 'iShares iBoxx $ High Yield Corp Bd ETF',
			index: 'BB Global HY',
			currency: 'SGD',
			weight: 19.05,
			alpha: 5.70,
			sharpeRatio: 0.50,
			jensenAlpha: 5.83,
			informationRatio: 1.83,
			trackingError: 3.11,
		},
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 16.05,
			alpha: 5.15,
			sharpeRatio: 0.34,
			jensenAlpha: 5.26,
			informationRatio: 2.26,
			trackingError: 2.28,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 1.00,
			alpha: 5.14,
			sharpeRatio: 0.65,
			jensenAlpha: 4.99,
			informationRatio: 1.62,
			trackingError: 2.92,
		},
		{
			name: 'PIMCO GIS GllnGd Crdt E SGD Inc',
			index: 'BB Global IG',
			currency: 'SGD',
			weight: 11.35,
			alpha: 1.81,
			sharpeRatio: 0.70,
			jensenAlpha: 2.22,
			informationRatio: 0.62,
			trackingError: 2.92,
		},
		{
			name: 'IShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB GLOBAL AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 0.90,
			jensenAlpha: 0.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 6.70,
			alpha: 1.63,
			sharpeRatio: 0.60,
			jensenAlpha: 1.66,
			informationRatio: 0.73,
			trackingError: 2.23,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 2.52,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'BGF Global Inflation Linked Bd A2 SGD',
			index: 'BB Dev Mkts Inflation Bonds',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.01,
			sharpeRatio: 0.06,
			jensenAlpha: 0.02,
			informationRatio: 0.00,
			trackingError: 2.46,
		},
		{
			name: 'iShares S&P 500 Growth ETF',
			index: 'S&P 500 Growth TR SGD',
			currency: 'SGD',
			weight: 10.01,
			alpha: 15.34,
			sharpeRatio: 0.09,
			jensenAlpha: 15.95,
			informationRatio: 0.35,
			trackingError: 43.76,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 6.40,
			alpha: 0.05,
			sharpeRatio: 0.25,
			jensenAlpha: 0.29,
			informationRatio: 0.03,
			trackingError: 1.44,
		},
		{
			name: 'Fidelity European Dynamic Gr A-Acc-EUR',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 6.40,
			alpha: 2.16,
			sharpeRatio: 0.41,
			jensenAlpha: 2.61,
			informationRatio: 0.36,
			trackingError: 6.07,
		},
		{
			name: 'iShares Core MSCI Emerging Markets ETF',
			index: 'MSCI EM IMI NR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 2.38,
			sharpeRatio: 0.16,
			jensenAlpha: 2.47,
			informationRatio: 0.52,
			trackingError: 4.54,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 1.00,
			alpha: 1.98,
			sharpeRatio: 0.09,
			jensenAlpha: 1.81,
			informationRatio: 0.60,
			trackingError: 3.33,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Jac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 3.08,
			alpha: 0.64,
			sharpeRatio: 0.14,
			jensenAlpha: 0.89,
			informationRatio: 0.09,
			trackingError: 6.84,
		},
		{
			name: 'Fidelity MSCI Communication ServicesETF',
			index: 'S&P500 Communication Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.15,
			sharpeRatio: 0.06,
			jensenAlpha: 1.24,
			informationRatio: 0.45,
			trackingError: 2.55,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.34,
			sharpeRatio: 0.28,
			jensenAlpha: 0.13,
			informationRatio: 0.09,
			trackingError: 3.69,
		},
		{
			name: 'iShares US Real Estate ETF',
			index: 'DJ US Real Estate TR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 3.86,
			sharpeRatio: 0.06,
			jensenAlpha: 3.89,
			informationRatio: 2.15,
			trackingError: 1.79,
		},
		{
			name: 'iShares International Dev Real Est ETF',
			index: 'FTSE EPRA Nareit Developed Ex US NR SGD',
			currency: 'SGD',
			weight: 2.00,
			alpha: 5.55,
			sharpeRatio: 0.35,
			jensenAlpha: 5.54,
			informationRatio: 1.17,
			trackingError: 4.73,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 7.00,
			alpha: 0.51,
			sharpeRatio: 0.22,
			jensenAlpha: 0.71,
			informationRatio: 0.10,
			trackingError: 5.30,
		},
	],
	'Core M1': [
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 15.28,
			alpha: 4.58,
			sharpeRatio: 0.23,
			jensenAlpha: 4.72,
			informationRatio: 1.27,
			trackingError: 3.60,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 14.29,
			alpha: 4.44,
			sharpeRatio: 0.96,
			jensenAlpha: 3.17,
			informationRatio: 0.81,
			trackingError: 5.46,
		},
		{
			name: 'IShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB GLOBAL AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 2.78,
			sharpeRatio: 1.15,
			jensenAlpha: 0.56,
			informationRatio: 0.34,
			trackingError: 8.13,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.32,
			sharpeRatio: 0.58,
			jensenAlpha: 0.70,
			informationRatio: 0.34,
			trackingError: 3.86,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 3.07,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'AIA International Health Care Fund',
			index: 'MSCI World/Health Care NR SGD',
			currency: 'SGD',
			weight: 14.55,
			alpha: 2.16,
			sharpeRatio: 0.05,
			jensenAlpha: 1.54,
			informationRatio: 0.31,
			trackingError: 6.86,
		},
		{
			name: 'iShares S&P 500 Value ETF',
			index: 'S&P 500 Value TR SGD',
			currency: 'SGD',
			weight: 10.00,
			alpha: 1.24,
			sharpeRatio: 0.18,
			jensenAlpha: 1.17,
			informationRatio: 0.52,
			trackingError: 2.38,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Pac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 4.42,
			alpha: 2.35,
			sharpeRatio: 0.12,
			jensenAlpha: 2.33,
			informationRatio: 0.34,
			trackingError: 6.98,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.06,
			sharpeRatio: 0.07,
			jensenAlpha: 0.12,
			informationRatio: 0.01,
			trackingError: 6.88,
		},
		{
			name: 'Fidelity AE MSCI Consumer Staples ETF',
			index: 'S&P500 Consumer Staples',
			currency: 'SGD',
			weight: 5.08,
			alpha: 2.57,
			sharpeRatio: 0.19,
			jensenAlpha: 2.52,
			informationRatio: 1.46,
			trackingError: 1.76,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 6.51,
			alpha: 0.60,
			sharpeRatio: 0.06,
			jensenAlpha: 0.59,
			informationRatio: 0.11,
			trackingError: 5.21,
		},
	],
	'Core M2': [
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 15.15,
			alpha: 4.96,
			sharpeRatio: 0.52,
			jensenAlpha: 4.92,
			informationRatio: 1.69,
			trackingError: 2.94,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 15.14,
			alpha: 4.72,
			sharpeRatio: 0.92,
			jensenAlpha: 3.95,
			informationRatio: 1.10,
			trackingError: 4.30,
		},
		{
			name: 'iShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB Global AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.17,
			jensenAlpha: 1.41,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.79,
			sharpeRatio: 0.79,
			jensenAlpha: 1.89,
			informationRatio: 0.59,
			trackingError: 3.02,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 3.60,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'BGF Global Inflation Linked Bd A2 SGD',
			index: 'BB Dev Mkts Inflation Bonds',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.59,
			sharpeRatio: 0.46,
			jensenAlpha: 0.64,
			informationRatio: 0.31,
			trackingError: 1.91,
		},
		{
			name: 'Fidelity European Dynamic Gr A-Acc-EUR',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.58,
			alpha: 1.97,
			sharpeRatio: 0.12,
			jensenAlpha: 1.98,
			informationRatio: 0.29,
			trackingError: 6.78,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.58,
			alpha: 0.27,
			sharpeRatio: 0.02,
			jensenAlpha: 0.27,
			informationRatio: 0.14,
			trackingError: 1.92,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 3.43,
			alpha: 2.57,
			sharpeRatio: 0.01,
			jensenAlpha: 2.34,
			informationRatio: 0.61,
			trackingError: 4.18,
		},
		{
			name: 'SPDR MSCI World Comm Svcs ETF SGD Acc',
			index: 'MSCI World Comm Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.04,
			sharpeRatio: 0.09,
			jensenAlpha: 0.09,
			informationRatio: 0.01,
			trackingError: 5.33,
		},
		{
			name: 'Health Care Select Sector SPDR ETF',
			index: 'S&P500 Health Care',
			currency: 'SGD',
			weight: 7.58,
			alpha: 1.76,
			sharpeRatio: 0.24,
			jensenAlpha: 1.69,
			informationRatio: 1.63,
			trackingError: 1.08,
		},
		{
			name: 'Wellington Gold HlthC Eq G SGD Acc Unh',
			index: 'S&P500 Health Care',
			currency: 'SGD',
			weight: 7.58,
			alpha: 1.54,
			sharpeRatio: 0.13,
			jensenAlpha: 1.88,
			informationRatio: 0.19,
			trackingError: 7.93,
		},
		{
			name: 'Communication Services Sel Sect SPDR ETF',
			index: 'S&P500 Communication Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.36,
			sharpeRatio: 0.15,
			jensenAlpha: 1.61,
			informationRatio: 0.81,
			trackingError: 1.67,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.15,
			sharpeRatio: 0.14,
			jensenAlpha: 0.29,
			informationRatio: 0.03,
			trackingError: 5.07,
		},
		{
			name: 'iShares US Real Estate ETF',
			index: 'DJ US Real Estate TR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 3.17,
			sharpeRatio: 0.03,
			jensenAlpha: 3.19,
			informationRatio: 1.99,
			trackingError: 1.59,
		},
		{
			name: 'iShares International Dev Real Est ETF',
			index: 'FTSE EPRA Nareit Developed Ex US NR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 4.79,
			sharpeRatio: 0.49,
			jensenAlpha: 4.68,
			informationRatio: 1.06,
			trackingError: 4.50,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 9.72,
			alpha: 0.71,
			sharpeRatio: 0.06,
			jensenAlpha: 0.68,
			informationRatio: 0.15,
			trackingError: 4.89,
		},
	],
	'Core M3': [
		{
			name: 'iShares iBoxx $ High Yield Corp Bd ETF',
			index: 'BB Gold HY',
			currency: 'SGD',
			weight: 10.00,
			alpha: 5.70,
			sharpeRatio: 0.70,
			jensenAlpha: 5.61,
			informationRatio: 1.83,
			trackingError: 3.11,
		},
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 20.00,
			alpha: 5.15,
			sharpeRatio: 0.55,
			jensenAlpha: 5.17,
			informationRatio: 2.26,
			trackingError: 2.28,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 15.00,
			alpha: 5.14,
			sharpeRatio: 0.80,
			jensenAlpha: 4.87,
			informationRatio: 1.62,
			trackingError: 3.17,
		},
		{
			name: 'PIMCO GIS GllnGd Crdt E SGD Inc',
			index: 'BB Global IG',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.81,
			sharpeRatio: 1.07,
			jensenAlpha: 2.64,
			informationRatio: 0.62,
			trackingError: 2.92,
		},
		{
			name: 'iShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB Global AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 4.04,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'BGF Global Inflation Linked Bd A2 SGD',
			index: 'BB Dev Mkts Inflation Bonds',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.01,
			sharpeRatio: 0.42,
			jensenAlpha: 0.23,
			informationRatio: 0.00,
			trackingError: 2.46,
		},
		{
			name: 'iShares S&P 500 Growth ETF',
			index: 'S&P 500 Growth TR SGD',
			currency: 'SGD',
			weight: 15.00,
			alpha: 15.34,
			sharpeRatio: 0.13,
			jensenAlpha: 15.85,
			informationRatio: 0.35,
			trackingError: 43.76,
		},
		{
			name: 'Fidelity European Dynamic Gr A-Acc-EUR',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 2.16,
			sharpeRatio: 0.29,
			jensenAlpha: 2.42,
			informationRatio: 0.36,
			trackingError: 6.07,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 0.05,
			sharpeRatio: 0.14,
			jensenAlpha: 0.29,
			informationRatio: 0.03,
			trackingError: 1.44,
		},
		{
			name: 'iShares Core MSCI Emerging Markets ETF',
			index: 'MSCI EM IMI NR SGD',
			currency: 'SGD',
			weight: 5.00,
			alpha: 2.38,
			sharpeRatio: 0.26,
			jensenAlpha: 2.49,
			informationRatio: 0.52,
			trackingError: 4.54,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 1.00,
			alpha: 1.98,
			sharpeRatio: 0.01,
			jensenAlpha: 1.92,
			informationRatio: 0.60,
			trackingError: 3.33,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Pac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.64,
			sharpeRatio: 0.02,
			jensenAlpha: 0.57,
			informationRatio: 0.09,
			trackingError: 6.84,
		},
		{
			name: 'Fidelity MSCI Communication ServicesETF',
			index: 'S&P500 Communication Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.15,
			sharpeRatio: 0.04,
			jensenAlpha: 1.26,
			informationRatio: 0.45,
			trackingError: 2.55,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.34,
			sharpeRatio: 0.16,
			jensenAlpha: 0.21,
			informationRatio: 0.09,
			trackingError: 3.69,
		},
		{
			name: 'iShares US Real Estate ETF',
			index: 'DJ US Real Estate TR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 3.86,
			sharpeRatio: 0.03,
			jensenAlpha: 3.88,
			informationRatio: 2.15,
			trackingError: 1.79,
		},
		{
			name: 'iShares International Dev Real Est ETF',
			index: 'FTSE EPRA Nareit Developed Ex US NR SGD',
			currency: 'SGD',
			weight: 8.00,
			alpha: 5.55,
			sharpeRatio: 0.45,
			jensenAlpha: 5.53,
			informationRatio: 1.17,
			trackingError: 4.73,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.51,
			sharpeRatio: 0.35,
			jensenAlpha: 0.84,
			informationRatio: 0.10,
			trackingError: 5.30,
		},
	],
	'Core G1': [
		{
			name: 'iShares iBoxx $ High Yield Corp Bd ETF',
			index: 'BB Gold HY',
			currency: 'SGD',
			weight: 10.00,
			alpha: 5.70,
			sharpeRatio: 0.70,
			jensenAlpha: 5.61,
			informationRatio: 1.83,
			trackingError: 3.11,
		},
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 20.00,
			alpha: 5.15,
			sharpeRatio: 0.55,
			jensenAlpha: 5.17,
			informationRatio: 2.26,
			trackingError: 2.28,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 15.00,
			alpha: 5.14,
			sharpeRatio: 0.80,
			jensenAlpha: 4.87,
			informationRatio: 1.62,
			trackingError: 3.17,
		},
		{
			name: 'PIMCO GIS GllnGd Crdt E SGD Inc',
			index: 'BB Global IG',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.81,
			sharpeRatio: 1.07,
			jensenAlpha: 2.64,
			informationRatio: 0.62,
			trackingError: 2.92,
		},
		{
			name: 'iShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB Global AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 4.04,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'BGF Global Inflation Linked Bd A2 SGD',
			index: 'BB Dev Mkts Inflation Bonds',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.01,
			sharpeRatio: 0.42,
			jensenAlpha: 0.23,
			informationRatio: 0.00,
			trackingError: 2.46,
		},
		{
			name: 'iShares S&P 500 Growth ETF',
			index: 'S&P 500 Growth TR SGD',
			currency: 'SGD',
			weight: 15.00,
			alpha: 15.34,
			sharpeRatio: 0.13,
			jensenAlpha: 15.85,
			informationRatio: 0.35,
			trackingError: 43.76,
		},
		{
			name: 'Fidelity European Dynamic Gr A-Acc-EUR',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 2.16,
			sharpeRatio: 0.29,
			jensenAlpha: 2.42,
			informationRatio: 0.36,
			trackingError: 6.07,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 0.05,
			sharpeRatio: 0.14,
			jensenAlpha: 0.29,
			informationRatio: 0.03,
			trackingError: 1.44,
		},
		{
			name: 'iShares Core MSCI Emerging Markets ETF',
			index: 'MSCI EM IMI NR SGD',
			currency: 'SGD',
			weight: 5.00,
			alpha: 2.38,
			sharpeRatio: 0.26,
			jensenAlpha: 2.49,
			informationRatio: 0.52,
			trackingError: 4.54,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 1.00,
			alpha: 1.98,
			sharpeRatio: 0.01,
			jensenAlpha: 1.92,
			informationRatio: 0.60,
			trackingError: 3.33,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Pac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.64,
			sharpeRatio: 0.02,
			jensenAlpha: 0.57,
			informationRatio: 0.09,
			trackingError: 6.84,
		},
		{
			name: 'Fidelity MSCI Communication ServicesETF',
			index: 'S&P500 Communication Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.15,
			sharpeRatio: 0.04,
			jensenAlpha: 1.26,
			informationRatio: 0.45,
			trackingError: 2.55,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.34,
			sharpeRatio: 0.16,
			jensenAlpha: 0.21,
			informationRatio: 0.09,
			trackingError: 3.69,
		},
		{
			name: 'iShares US Real Estate ETF',
			index: 'DJ US Real Estate TR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 3.86,
			sharpeRatio: 0.03,
			jensenAlpha: 3.88,
			informationRatio: 2.15,
			trackingError: 1.79,
		},
		{
			name: 'iShares International Dev Real Est ETF',
			index: 'FTSE EPRA Nareit Developed Ex US NR SGD',
			currency: 'SGD',
			weight: 8.00,
			alpha: 5.55,
			sharpeRatio: 0.45,
			jensenAlpha: 5.53,
			informationRatio: 1.17,
			trackingError: 4.73,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.51,
			sharpeRatio: 0.35,
			jensenAlpha: 0.84,
			informationRatio: 0.10,
			trackingError: 5.30,
		},
	],
	'Core G2': [
		{
			name: 'iShares iBoxx $ High Yield Corp Bd ETF',
			index: 'BB Gold HY',
			currency: 'SGD',
			weight: 10.00,
			alpha: 5.70,
			sharpeRatio: 0.70,
			jensenAlpha: 5.61,
			informationRatio: 1.83,
			trackingError: 3.11,
		},
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 20.00,
			alpha: 5.15,
			sharpeRatio: 0.55,
			jensenAlpha: 5.17,
			informationRatio: 2.26,
			trackingError: 2.28,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 15.00,
			alpha: 5.14,
			sharpeRatio: 0.80,
			jensenAlpha: 4.87,
			informationRatio: 1.62,
			trackingError: 3.17,
		},
		{
			name: 'PIMCO GIS GllnGd Crdt E SGD Inc',
			index: 'BB Global IG',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.81,
			sharpeRatio: 1.07,
			jensenAlpha: 2.64,
			informationRatio: 0.62,
			trackingError: 2.92,
		},
		{
			name: 'iShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB Global AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 4.04,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'BGF Global Inflation Linked Bd A2 SGD',
			index: 'BB Dev Mkts Inflation Bonds',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.01,
			sharpeRatio: 0.42,
			jensenAlpha: 0.23,
			informationRatio: 0.00,
			trackingError: 2.46,
		},
		{
			name: 'iShares S&P 500 Growth ETF',
			index: 'S&P 500 Growth TR SGD',
			currency: 'SGD',
			weight: 15.00,
			alpha: 15.34,
			sharpeRatio: 0.13,
			jensenAlpha: 15.85,
			informationRatio: 0.35,
			trackingError: 43.76,
		},
		{
			name: 'Fidelity European Dynamic Gr A-Acc-EUR',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 2.16,
			sharpeRatio: 0.29,
			jensenAlpha: 2.42,
			informationRatio: 0.36,
			trackingError: 6.07,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 0.05,
			sharpeRatio: 0.14,
			jensenAlpha: 0.29,
			informationRatio: 0.03,
			trackingError: 1.44,
		},
		{
			name: 'iShares Core MSCI Emerging Markets ETF',
			index: 'MSCI EM IMI NR SGD',
			currency: 'SGD',
			weight: 5.00,
			alpha: 2.38,
			sharpeRatio: 0.26,
			jensenAlpha: 2.49,
			informationRatio: 0.52,
			trackingError: 4.54,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 1.00,
			alpha: 1.98,
			sharpeRatio: 0.01,
			jensenAlpha: 1.92,
			informationRatio: 0.60,
			trackingError: 3.33,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Pac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.64,
			sharpeRatio: 0.02,
			jensenAlpha: 0.57,
			informationRatio: 0.09,
			trackingError: 6.84,
		},
		{
			name: 'Fidelity MSCI Communication ServicesETF',
			index: 'S&P500 Communication Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.15,
			sharpeRatio: 0.04,
			jensenAlpha: 1.26,
			informationRatio: 0.45,
			trackingError: 2.55,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.34,
			sharpeRatio: 0.16,
			jensenAlpha: 0.21,
			informationRatio: 0.09,
			trackingError: 3.69,
		},
		{
			name: 'iShares US Real Estate ETF',
			index: 'DJ US Real Estate TR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 3.86,
			sharpeRatio: 0.03,
			jensenAlpha: 3.88,
			informationRatio: 2.15,
			trackingError: 1.79,
		},
		{
			name: 'iShares International Dev Real Est ETF',
			index: 'FTSE EPRA Nareit Developed Ex US NR SGD',
			currency: 'SGD',
			weight: 8.00,
			alpha: 5.55,
			sharpeRatio: 0.45,
			jensenAlpha: 5.53,
			informationRatio: 1.17,
			trackingError: 4.73,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.51,
			sharpeRatio: 0.35,
			jensenAlpha: 0.84,
			informationRatio: 0.10,
			trackingError: 5.30,
		},
	],
	'Core G3': [
		{
			name: 'iShares iBoxx $ High Yield Corp Bd ETF',
			index: 'BB Gold HY',
			currency: 'SGD',
			weight: 10.00,
			alpha: 5.70,
			sharpeRatio: 0.70,
			jensenAlpha: 5.61,
			informationRatio: 1.83,
			trackingError: 3.11,
		},
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 20.00,
			alpha: 5.15,
			sharpeRatio: 0.55,
			jensenAlpha: 5.17,
			informationRatio: 2.26,
			trackingError: 2.28,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 15.00,
			alpha: 5.14,
			sharpeRatio: 0.80,
			jensenAlpha: 4.87,
			informationRatio: 1.62,
			trackingError: 3.17,
		},
		{
			name: 'PIMCO GIS GllnGd Crdt E SGD Inc',
			index: 'BB Global IG',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.81,
			sharpeRatio: 1.07,
			jensenAlpha: 2.64,
			informationRatio: 0.62,
			trackingError: 2.92,
		},
		{
			name: 'iShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB Global AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 4.04,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'BGF Global Inflation Linked Bd A2 SGD',
			index: 'BB Dev Mkts Inflation Bonds',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.01,
			sharpeRatio: 0.42,
			jensenAlpha: 0.23,
			informationRatio: 0.00,
			trackingError: 2.46,
		},
		{
			name: 'iShares S&P 500 Growth ETF',
			index: 'S&P 500 Growth TR SGD',
			currency: 'SGD',
			weight: 15.00,
			alpha: 15.34,
			sharpeRatio: 0.13,
			jensenAlpha: 15.85,
			informationRatio: 0.35,
			trackingError: 43.76,
		},
		{
			name: 'Fidelity European Dynamic Gr A-Acc-EUR',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 2.16,
			sharpeRatio: 0.29,
			jensenAlpha: 2.42,
			informationRatio: 0.36,
			trackingError: 6.07,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 0.05,
			sharpeRatio: 0.14,
			jensenAlpha: 0.29,
			informationRatio: 0.03,
			trackingError: 1.44,
		},
		{
			name: 'iShares Core MSCI Emerging Markets ETF',
			index: 'MSCI EM IMI NR SGD',
			currency: 'SGD',
			weight: 5.00,
			alpha: 2.38,
			sharpeRatio: 0.26,
			jensenAlpha: 2.49,
			informationRatio: 0.52,
			trackingError: 4.54,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 1.00,
			alpha: 1.98,
			sharpeRatio: 0.01,
			jensenAlpha: 1.92,
			informationRatio: 0.60,
			trackingError: 3.33,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Pac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.64,
			sharpeRatio: 0.02,
			jensenAlpha: 0.57,
			informationRatio: 0.09,
			trackingError: 6.84,
		},
		{
			name: 'Fidelity MSCI Communication ServicesETF',
			index: 'S&P500 Communication Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.15,
			sharpeRatio: 0.04,
			jensenAlpha: 1.26,
			informationRatio: 0.45,
			trackingError: 2.55,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.34,
			sharpeRatio: 0.16,
			jensenAlpha: 0.21,
			informationRatio: 0.09,
			trackingError: 3.69,
		},
		{
			name: 'iShares US Real Estate ETF',
			index: 'DJ US Real Estate TR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 3.86,
			sharpeRatio: 0.03,
			jensenAlpha: 3.88,
			informationRatio: 2.15,
			trackingError: 1.79,
		},
		{
			name: 'iShares International Dev Real Est ETF',
			index: 'FTSE EPRA Nareit Developed Ex US NR SGD',
			currency: 'SGD',
			weight: 8.00,
			alpha: 5.55,
			sharpeRatio: 0.45,
			jensenAlpha: 5.53,
			informationRatio: 1.17,
			trackingError: 4.73,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.51,
			sharpeRatio: 0.35,
			jensenAlpha: 0.84,
			informationRatio: 0.10,
			trackingError: 5.30,
		},
	],
	'Core A1': [
		{
			name: 'iShares iBoxx $ High Yield Corp Bd ETF',
			index: 'BB Gold HY',
			currency: 'SGD',
			weight: 10.00,
			alpha: 5.70,
			sharpeRatio: 0.70,
			jensenAlpha: 5.61,
			informationRatio: 1.83,
			trackingError: 3.11,
		},
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 20.00,
			alpha: 5.15,
			sharpeRatio: 0.55,
			jensenAlpha: 5.17,
			informationRatio: 2.26,
			trackingError: 2.28,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 15.00,
			alpha: 5.14,
			sharpeRatio: 0.80,
			jensenAlpha: 4.87,
			informationRatio: 1.62,
			trackingError: 3.17,
		},
		{
			name: 'PIMCO GIS GllnGd Crdt E SGD Inc',
			index: 'BB Global IG',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.81,
			sharpeRatio: 1.07,
			jensenAlpha: 2.64,
			informationRatio: 0.62,
			trackingError: 2.92,
		},
		{
			name: 'iShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB Global AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 4.04,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'BGF Global Inflation Linked Bd A2 SGD',
			index: 'BB Dev Mkts Inflation Bonds',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.01,
			sharpeRatio: 0.42,
			jensenAlpha: 0.23,
			informationRatio: 0.00,
			trackingError: 2.46,
		},
		{
			name: 'iShares S&P 500 Growth ETF',
			index: 'S&P 500 Growth TR SGD',
			currency: 'SGD',
			weight: 15.00,
			alpha: 15.34,
			sharpeRatio: 0.13,
			jensenAlpha: 15.85,
			informationRatio: 0.35,
			trackingError: 43.76,
		},
		{
			name: 'Fidelity European Dynamic Gr A-Acc-EUR',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 2.16,
			sharpeRatio: 0.29,
			jensenAlpha: 2.42,
			informationRatio: 0.36,
			trackingError: 6.07,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 0.05,
			sharpeRatio: 0.14,
			jensenAlpha: 0.29,
			informationRatio: 0.03,
			trackingError: 1.44,
		},
		{
			name: 'iShares Core MSCI Emerging Markets ETF',
			index: 'MSCI EM IMI NR SGD',
			currency: 'SGD',
			weight: 5.00,
			alpha: 2.38,
			sharpeRatio: 0.26,
			jensenAlpha: 2.49,
			informationRatio: 0.52,
			trackingError: 4.54,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 1.00,
			alpha: 1.98,
			sharpeRatio: 0.01,
			jensenAlpha: 1.92,
			informationRatio: 0.60,
			trackingError: 3.33,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Pac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.64,
			sharpeRatio: 0.02,
			jensenAlpha: 0.57,
			informationRatio: 0.09,
			trackingError: 6.84,
		},
		{
			name: 'Fidelity MSCI Communication ServicesETF',
			index: 'S&P500 Communication Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.15,
			sharpeRatio: 0.04,
			jensenAlpha: 1.26,
			informationRatio: 0.45,
			trackingError: 2.55,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.34,
			sharpeRatio: 0.16,
			jensenAlpha: 0.21,
			informationRatio: 0.09,
			trackingError: 3.69,
		},
		{
			name: 'iShares US Real Estate ETF',
			index: 'DJ US Real Estate TR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 3.86,
			sharpeRatio: 0.03,
			jensenAlpha: 3.88,
			informationRatio: 2.15,
			trackingError: 1.79,
		},
		{
			name: 'iShares International Dev Real Est ETF',
			index: 'FTSE EPRA Nareit Developed Ex US NR SGD',
			currency: 'SGD',
			weight: 8.00,
			alpha: 5.55,
			sharpeRatio: 0.45,
			jensenAlpha: 5.53,
			informationRatio: 1.17,
			trackingError: 4.73,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.51,
			sharpeRatio: 0.35,
			jensenAlpha: 0.84,
			informationRatio: 0.10,
			trackingError: 5.30,
		},
	],
	'Core A2': [
		{
			name: 'iShares iBoxx $ High Yield Corp Bd ETF',
			index: 'BB Gold HY',
			currency: 'SGD',
			weight: 10.00,
			alpha: 5.70,
			sharpeRatio: 0.70,
			jensenAlpha: 5.61,
			informationRatio: 1.83,
			trackingError: 3.11,
		},
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 20.00,
			alpha: 5.15,
			sharpeRatio: 0.55,
			jensenAlpha: 5.17,
			informationRatio: 2.26,
			trackingError: 2.28,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 15.00,
			alpha: 5.14,
			sharpeRatio: 0.80,
			jensenAlpha: 4.87,
			informationRatio: 1.62,
			trackingError: 3.17,
		},
		{
			name: 'PIMCO GIS GllnGd Crdt E SGD Inc',
			index: 'BB Global IG',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.81,
			sharpeRatio: 1.07,
			jensenAlpha: 2.64,
			informationRatio: 0.62,
			trackingError: 2.92,
		},
		{
			name: 'iShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB Global AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 4.04,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'BGF Global Inflation Linked Bd A2 SGD',
			index: 'BB Dev Mkts Inflation Bonds',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.01,
			sharpeRatio: 0.42,
			jensenAlpha: 0.23,
			informationRatio: 0.00,
			trackingError: 2.46,
		},
		{
			name: 'iShares S&P 500 Growth ETF',
			index: 'S&P 500 Growth TR SGD',
			currency: 'SGD',
			weight: 15.00,
			alpha: 15.34,
			sharpeRatio: 0.13,
			jensenAlpha: 15.85,
			informationRatio: 0.35,
			trackingError: 43.76,
		},
		{
			name: 'Fidelity European Dynamic Gr A-Acc-EUR',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 2.16,
			sharpeRatio: 0.29,
			jensenAlpha: 2.42,
			informationRatio: 0.36,
			trackingError: 6.07,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 0.05,
			sharpeRatio: 0.14,
			jensenAlpha: 0.29,
			informationRatio: 0.03,
			trackingError: 1.44,
		},
		{
			name: 'iShares Core MSCI Emerging Markets ETF',
			index: 'MSCI EM IMI NR SGD',
			currency: 'SGD',
			weight: 5.00,
			alpha: 2.38,
			sharpeRatio: 0.26,
			jensenAlpha: 2.49,
			informationRatio: 0.52,
			trackingError: 4.54,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 1.00,
			alpha: 1.98,
			sharpeRatio: 0.01,
			jensenAlpha: 1.92,
			informationRatio: 0.60,
			trackingError: 3.33,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Pac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.64,
			sharpeRatio: 0.02,
			jensenAlpha: 0.57,
			informationRatio: 0.09,
			trackingError: 6.84,
		},
		{
			name: 'Fidelity MSCI Communication ServicesETF',
			index: 'S&P500 Communication Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.15,
			sharpeRatio: 0.04,
			jensenAlpha: 1.26,
			informationRatio: 0.45,
			trackingError: 2.55,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.34,
			sharpeRatio: 0.16,
			jensenAlpha: 0.21,
			informationRatio: 0.09,
			trackingError: 3.69,
		},
		{
			name: 'iShares US Real Estate ETF',
			index: 'DJ US Real Estate TR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 3.86,
			sharpeRatio: 0.03,
			jensenAlpha: 3.88,
			informationRatio: 2.15,
			trackingError: 1.79,
		},
		{
			name: 'iShares International Dev Real Est ETF',
			index: 'FTSE EPRA Nareit Developed Ex US NR SGD',
			currency: 'SGD',
			weight: 8.00,
			alpha: 5.55,
			sharpeRatio: 0.45,
			jensenAlpha: 5.53,
			informationRatio: 1.17,
			trackingError: 4.73,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.51,
			sharpeRatio: 0.35,
			jensenAlpha: 0.84,
			informationRatio: 0.10,
			trackingError: 5.30,
		},
	],
	'Core A3': [
		{
			name: 'iShares iBoxx $ High Yield Corp Bd ETF',
			index: 'BB Gold HY',
			currency: 'SGD',
			weight: 10.00,
			alpha: 5.70,
			sharpeRatio: 0.70,
			jensenAlpha: 5.61,
			informationRatio: 1.83,
			trackingError: 3.11,
		},
		{
			name: 'iShares JP Morgan SGD Em Mkts Bd ETF',
			index: 'BB EM Asia Credit SGD',
			currency: 'SGD',
			weight: 20.00,
			alpha: 5.15,
			sharpeRatio: 0.55,
			jensenAlpha: 5.17,
			informationRatio: 2.26,
			trackingError: 2.28,
		},
		{
			name: 'Invesco Emerging Markets Sov Debt ETF',
			index: 'BB EM Government',
			currency: 'SGD',
			weight: 15.00,
			alpha: 5.14,
			sharpeRatio: 0.80,
			jensenAlpha: 4.87,
			informationRatio: 1.62,
			trackingError: 3.17,
		},
		{
			name: 'PIMCO GIS GllnGd Crdt E SGD Inc',
			index: 'BB Global IG',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.81,
			sharpeRatio: 1.07,
			jensenAlpha: 2.64,
			informationRatio: 0.62,
			trackingError: 2.92,
		},
		{
			name: 'iShares Core Glbl Aggg Bond UCITS ETF',
			index: 'BB Global AGGS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'iShares TIPS Bond ETF',
			index: 'BB US TIPS',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.53,
			sharpeRatio: 1.19,
			jensenAlpha: 1.47,
			informationRatio: 0.22,
			trackingError: 6.86,
		},
		{
			name: 'DFA Two-Year Global Fixed-Income I',
			index: 'BB Global Sht Duration',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.00,
			sharpeRatio: 4.04,
			jensenAlpha: 0.00,
			informationRatio: 0.00,
			trackingError: 0.00,
		},
		{
			name: 'BGF Global Inflation Linked Bd A2 SGD',
			index: 'BB Dev Mkts Inflation Bonds',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.01,
			sharpeRatio: 0.42,
			jensenAlpha: 0.23,
			informationRatio: 0.00,
			trackingError: 2.46,
		},
		{
			name: 'iShares S&P 500 Growth ETF',
			index: 'S&P 500 Growth TR SGD',
			currency: 'SGD',
			weight: 15.00,
			alpha: 15.34,
			sharpeRatio: 0.13,
			jensenAlpha: 15.85,
			informationRatio: 0.35,
			trackingError: 43.76,
		},
		{
			name: 'Fidelity European Dynamic Gr A-Acc-EUR',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 2.16,
			sharpeRatio: 0.29,
			jensenAlpha: 2.42,
			informationRatio: 0.36,
			trackingError: 6.07,
		},
		{
			name: 'Lyxor Core STOXX Europe 600(DR) ETF Acc',
			index: 'EUROPE 600',
			currency: 'EUR',
			weight: 7.00,
			alpha: 0.05,
			sharpeRatio: 0.14,
			jensenAlpha: 0.29,
			informationRatio: 0.03,
			trackingError: 1.44,
		},
		{
			name: 'iShares Core MSCI Emerging Markets ETF',
			index: 'MSCI EM IMI NR SGD',
			currency: 'SGD',
			weight: 5.00,
			alpha: 2.38,
			sharpeRatio: 0.26,
			jensenAlpha: 2.49,
			informationRatio: 0.52,
			trackingError: 4.54,
		},
		{
			name: 'iShares S&P Nikkei 400 ETF',
			index: 'Japan (TPX)',
			currency: 'JPY',
			weight: 1.00,
			alpha: 1.98,
			sharpeRatio: 0.01,
			jensenAlpha: 1.92,
			informationRatio: 0.60,
			trackingError: 3.33,
		},
		{
			name: 'Nikko AM Shenton Asia Pacific',
			index: 'MSCI AC Asia Pac Ex JPN NR SGD',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.64,
			sharpeRatio: 0.02,
			jensenAlpha: 0.57,
			informationRatio: 0.09,
			trackingError: 6.84,
		},
		{
			name: 'Fidelity MSCI Communication ServicesETF',
			index: 'S&P500 Communication Services',
			currency: 'SGD',
			weight: 1.00,
			alpha: 1.15,
			sharpeRatio: 0.04,
			jensenAlpha: 1.26,
			informationRatio: 0.45,
			trackingError: 2.55,
		},
		{
			name: 'SPDR MSCI World Utilities ETF SGD Acc',
			index: 'MSCI World Utilities',
			currency: 'SGD',
			weight: 2.00,
			alpha: 0.34,
			sharpeRatio: 0.16,
			jensenAlpha: 0.21,
			informationRatio: 0.09,
			trackingError: 3.69,
		},
		{
			name: 'iShares US Real Estate ETF',
			index: 'DJ US Real Estate TR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 3.86,
			sharpeRatio: 0.03,
			jensenAlpha: 3.88,
			informationRatio: 2.15,
			trackingError: 1.79,
		},
		{
			name: 'iShares International Dev Real Est ETF',
			index: 'FTSE EPRA Nareit Developed Ex US NR SGD',
			currency: 'SGD',
			weight: 8.00,
			alpha: 5.55,
			sharpeRatio: 0.45,
			jensenAlpha: 5.53,
			informationRatio: 1.17,
			trackingError: 4.73,
		},
		{
			name: 'SPDR Gold Shares ETF',
			index: 'LBMA Gold Price PM PR SGD',
			currency: 'SGD',
			weight: 1.00,
			alpha: 0.51,
			sharpeRatio: 0.35,
			jensenAlpha: 0.84,
			informationRatio: 0.10,
			trackingError: 5.30,
		},
	],
};

export default data;
